### ISSUE TITLE
升级到flutter 3.29 出现如下错误

### ISSUE THREAD

**Issue by joo** [rhymelph/r_upgrade#99]
/home/joo/.pub-cache/hosted/pub.flutter-io.cn/r_upgrade-0.4.2/android/src/main/java/com/example/r_upgrade/RUpgradePlugin.java:19: 错误: 找不到符号
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  符号:   类 Registrar
  位置: 接口 PluginRegistry
/home/joo/.pub-cache/hosted/pub.flutter-io.cn/r_upgrade-0.4.2/android/src/main/java/com/example/r_upgrade/RUpgradePlugin.java:48: 错误: 找不到符号
    public static void registerWith(final Registrar registrar) {
                                          ^
  符号:   类 Registrar
  位置: 类 RUpgradePlugin

**Comment by planitian** [comment]
我也是这样的，有解决方法么？

**Comment by Sahad2701** [comment]
Hi , @joo  Please update your **pubspec.yaml** file replace r_upgrade: ^0.4.2 with below code and also use command `flutter pub catch clean` and then` flutter pub get` will solve your issue.

I have forked this plugin and removed **PluginRegistry** Apis.


```
r_upgrade:
    git:
      url: https://github.com/Sahad2701/r_upgrade.git
      ref: fix/remove-pluginregistry-usage
```
